---
openvpn_server_enabled: false
openvpn_client_enabled: false
openvpn_host: vpn.fabinfra.net
openvpn_port: 1194
openvpn_ca: |
  -----BEGIN CERTIFICATE-----
  MIIDbjCCAlagAwIBAgIRAK1yxU+9CzwW8Wu/lNm69UgwDQYJKoZIhvcNAQELBQAw
  XjELMAkGA1UEBhMCRlIxETAPBgNVBAoTCEZDIFByb2QuMRkwFwYDVQQDExBGQyBQ
  cm9kLiBSb290IENBMSEwHwYJKoZIhvcNAQkBFhJmYWJpZW5AY3Jlc3BlbC5uZXQw
  HhcNMjIwNDE4MTU0MDE5WhcNMzIwNDE1MTU0MDE5WjAiMSAwHgYDVQQDExdGYWJJ
  bmZyYSBQcm9kdWN0aW9uIENBMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
  ggEBAMQt1AGqilfvNGQlbaTimLV03lIy15ocIon+3SN95bqgBOALblczzOLig6bT
  euPnwmlpVx0Wj8tt64eMn77sP3jPv9it4Kobn4ngB0OEmjCmhZU/nPRDxqTLeGec
  9U68EMAsq3WR0BW+sXixBiySnCTXxM1Tq++sIVwrE0eLvayv547uSVizNm+inMG5
  S+SJEpY44qF2CErdXUftCevQgxgF619Pf4126NR7D/3F71VA4zcAV0EuwvgYDbAV
  2SvPsnPlNwLLdhQwEvgdtdv5ATRBh+J6wu7F76iVUvj2NIW/2/qn3fXt38pe6JED
  8LHUsnHBJSjB1+FK3byXTmcF9BUCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgKkMA8G
  A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFFI94aVHaSIOnEKb9P09Jheoj4nQMB8G
  A1UdIwQYMBaAFIZSn7Y53+H3C6P3DNxOYAirKGUEMA0GCSqGSIb3DQEBCwUAA4IB
  AQAIwZaLTCsK3QutLwD9gF1UEaYMlyMx/gySYzGafeX8tiXc8VfP34m9gbgzCTY9
  LfH5MD0fibZqjxDotdXpHAerVYMMvTFrveKNgtm9fyNcL0uC+MpVSsfcAjCftHd/
  JVVg1gk5HS9H9SdH3A+sqq6KF0swX7NPnHYQnoUPS8w1cr1QIbLBm4EB/NvWASv4
  82eXM+DS1N1ghYiGd5m7KLVT8L2dbgzg4eLP2XWNjmB5PKs2CP7gN7nscAuCMSvC
  MW37wWTo679Iy7zcwR+LxZwo/18jcOVmDT5WlAcPu9bkc/PZAeUYVwnxjc0STg+o
  H7rdnscsy/RyCLDF5NX39vei
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIElDCCA3ygAwIBAgIJALHUTcMiI7jmMA0GCSqGSIb3DQEBBQUAMF4xCzAJBgNV
  BAYTAkZSMREwDwYDVQQKEwhGQyBQcm9kLjEZMBcGA1UEAxMQRkMgUHJvZC4gUm9v
  dCBDQTEhMB8GCSqGSIb3DQEJARYSZmFiaWVuQGNyZXNwZWwubmV0MB4XDTE4MDYz
  MDIwNDIwOFoXDTM4MDYyNTIwNDIwOFowXjELMAkGA1UEBhMCRlIxETAPBgNVBAoT
  CEZDIFByb2QuMRkwFwYDVQQDExBGQyBQcm9kLiBSb290IENBMSEwHwYJKoZIhvcN
  AQkBFhJmYWJpZW5AY3Jlc3BlbC5uZXQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
  ggEKAoIBAQC07zXwcHFR0oFPetI11BDFHoYzGz3c8nFI+NIB17ftokkZyrK95oms
  tEduxPiW28XpDmo3dwqRB6acpadTvt/k1UG1auqBxlRmhjKFE6nXBSaWerjguJ6U
  quxdhM4Mtz+aq1dBNLslZTh9/4r39QxPbWJeTl/lxgXoIInCmCwVfnwYz8uBmK09
  59dkqyVejJKGGHDJP8mxlACOuDYxvkvHJhXytzLAX4I1MDBLw0FfSXc3EAZombFX
  srylS7PPZmFuNBYSEYiBFe+Ah4Ue4ef0qE4YCyJFlqTZ9YhnAflIQPoyv/Jf+yNP
  g+GQbfgpg59FtNb3mDFIIxOAFsfTxmBVAgMBAAGjggFTMIIBTzAPBgNVHRMBAf8E
  BTADAQH/MCwGCWCGSAGG+EIBDQQfFh1ZYVNUIEdlbmVyYXRlZCBDQSBDZXJ0aWZp
  Y2F0ZTARBglghkgBhvhCAQEEBAMCAQYwCwYDVR0PBAQDAgEGMB0GA1UdDgQWBBSG
  Up+2Od/h9wuj9wzcTmAIqyhlBDCBkAYDVR0jBIGIMIGFgBSGUp+2Od/h9wuj9wzc
  TmAIqyhlBKFipGAwXjELMAkGA1UEBhMCRlIxETAPBgNVBAoTCEZDIFByb2QuMRkw
  FwYDVQQDExBGQyBQcm9kLiBSb290IENBMSEwHwYJKoZIhvcNAQkBFhJmYWJpZW5A
  Y3Jlc3BlbC5uZXSCCQCx1E3DIiO45jAdBgNVHREEFjAUgRJmYWJpZW5AY3Jlc3Bl
  bC5uZXQwHQYDVR0SBBYwFIESZmFiaWVuQGNyZXNwZWwubmV0MA0GCSqGSIb3DQEB
  BQUAA4IBAQBVQ2rkhrjxbxeHuxVAojH/8zlWt3xDlpSEOWdXU5vW4HN96JlRcQws
  73OMZr3pXCMhLHitLz+Vq1Qd2PAoiPuA9NOxCCqYDTxbVMoJNuOZB/CWnxIU7tUj
  f1k2KRyDqZeaBc3cVFI0WUUh6hnV2C/4mAZ3vEDc50oe9bIaAI4MtRI9iqsy0LGy
  4Y98cQrZdR84uB+fLopPKMJME2ueOOjRTr4M6L0x6enBJHKvF9x0n2EA7Fxt16/e
  W/xQks2o2o/tHkybC/+BNKMWCjTHpVv7LEZSPCqKcNX5alDCWRhrGpuN6NiQrcOf
  lUMJGP/FKuOxMWGL4ymrkgbCbydSivC1
  -----END CERTIFICATE-----
openvpn_cert: "{{vault_openvpn_cert}}"
openvpn_key: "{{vault_openvpn_key}}"
openvpn_dh: "{{vault_openvpn_dh}}"
skip_services: false
