version: "3.5"
services:
  # Ansible on Debian 11
  # docker-compose run --rm debian11 [args ...]
  debian11:
    image: serverconfig:debian11
    build:
      context: .
      args:
        BASE_IMAGE: debian:11
    hostname: localhost
    volumes:
      - '.:/serverconfig'

  # Ansible on Debian 12
  # docker-compose run --rm debian12 [args ...]
  debian12:
    image: serverconfig:debian12
    build:
      context: .
      args:
        BASE_IMAGE: debian:12
    hostname: localhost
    volumes:
      - '.:/serverconfig'

  # Ansible on Rocky Linux 8
  # docker-compose run --rm rocky8 [args ...]
  rocky8:
    image: serverconfig:rocky8
    build:
      context: .
      args:
        BASE_IMAGE: rockylinux:8
    hostname: localhost
    volumes:
      - '.:/serverconfig'

  # Ansible on Rocky Linux 9
  # docker-compose run --rm rocky9 [args ...]
  rocky9:
    image: serverconfig:rocky9
    build:
      context: .
      args:
        BASE_IMAGE: rockylinux:9
    hostname: localhost
    volumes:
      - '.:/serverconfig'

  # Ansible on Ubuntu 22.04
  # docker-compose run --rm ubuntu2204 [args ...]
  ubuntu2204:
    image: serverconfig:ubuntu2204
    build:
      context: .
      args:
        BASE_IMAGE: ubuntu:22.04
    hostname: localhost
    volumes:
      - '.:/serverconfig'
