version: "3.5"
services:
  # Ansible on CentOS 7
  # docker-compose run --rm centos7 [args ...]
  centos7:
    image: serverconfig:centos7
    build:
      context: .
      args:
        BASE_IMAGE: centos:7
    hostname: localhost
    volumes:
      - '.:/serverconfig'

  # Ansible on Debian 10
  # docker-compose run --rm debian10 [args ...]
  debian10:
    image: serverconfig:debian10
    build:
      context: .
      args:
        BASE_IMAGE: debian:10
    hostname: localhost
    volumes:
      - '.:/serverconfig'

  # Ansible on Debian 11
  # docker-compose run --rm debian11 [args ...]
  debian11:
    image: serverconfig:debian11
    build:
      context: .
      args:
        BASE_IMAGE: debian:11
    hostname: localhost
    volumes:
      - '.:/serverconfig'

  # Ansible on Rocky Linux 8
  # docker-compose run --rm rocky8 [args ...]
  rocky8:
    image: serverconfig:rocky8
    build:
      context: .
      args:
        BASE_IMAGE: rockylinux:8
    hostname: localhost
    volumes:
      - '.:/serverconfig'

  # Ansible on Ubuntu 20.04
  # docker-compose run --rm ubuntu2004 [args ...]
  ubuntu2004:
    image: serverconfig:ubuntu2004
    build:
      context: .
      args:
        BASE_IMAGE: ubuntu:20.04
    hostname: localhost
    volumes:
      - '.:/serverconfig'

  # Ansible Vault utility
  # docker-compose run --rm vault <action> [args ...]
  vault:
    image: serverconfig:centos7
    build:
      context: .
      args:
        BASE_IMAGE: centos:7
    entrypoint: ['ansible-vault']
    environment:
      - ANSIBLE_VAULT_PASSWORD_FILE=vault.password
    volumes:
      - '.:/serverconfig'
