---
# Server configuration playbook

- name: Common setup
  hosts: all
  tasks:
    - name: Include role
      include_role:
        name: "{{roleName}}"
        apply:
          tags: "{{roleName}}"
      tags: always
      loop_control:
        loop_var: "roleName"
      with_items:
        - base
        - grafana-agent
        - openvpn

- name: Kubernetes setup
  hosts: k8s
  gather_facts: no
  tasks:
    - name: Include role
      include_role:
        name: "{{roleName}}"
        apply:
          tags: "{{roleName}}"
      tags: always
      loop_control:
        loop_var: "roleName"
      with_items:
        - k8s
