---
# Server configuration playbook

- name: Common setup
  hosts: all
  tasks:
    - name: Include role
      include_role:
        name: "{{roleName}}"
        apply:
          tags: "{{roleName}}"
      tags: always
      loop_control:
        loop_var: "roleName"
      loop:
        - base
        - firewall
        - openvpn
        - otelcol
        - docker

- name: Kubernetes setup
  hosts: k8s
  gather_facts: no
  tasks:
    - name: Include role
      include_role:
        name: "{{roleName}}"
        apply:
          tags: "{{roleName}}"
      tags: always
      loop_control:
        loop_var: "roleName"
      loop:
        - k8s

- name: Home server setup
  hosts: homeserver
  gather_facts: no
  tasks:
    - name: Include role
      include_role:
        name: "{{roleName}}"
        apply:
          tags: "{{roleName}}"
      tags: always
      loop_control:
        loop_var: "roleName"
      loop:
        - homeserver

- name: Media center setup
  hosts: mediacenter
  gather_facts: no
  tasks:
    - name: Include role
      include_role:
        name: "{{roleName}}"
        apply:
          tags: "{{roleName}}"
      tags: always
      loop_control:
        loop_var: "roleName"
      loop:
        - kodi
