---
# Server configuration playbook

- name: Common setup
  hosts: all
  tasks:
    - name: Include role
      include_role:
        name: "{{roleName}}"
        apply:
          tags: "{{roleName}}"
      tags: always
      loop_control:
        loop_var: "roleName"
      loop:
        - base
        - firewall
        - grafana-agent
        - openvpn

- name: Kubernetes setup
  hosts: k8s
  gather_facts: no
  tasks:
    - name: Include role
      include_role:
        name: "{{roleName}}"
        apply:
          tags: "{{roleName}}"
      tags: always
      loop_control:
        loop_var: "roleName"
      loop:
        - k8s

- name: Docker setup
  hosts: "!k8s"
  gather_facts: no
  tasks:
    - name: Include role
      include_role:
        name: "{{roleName}}"
        apply:
          tags: "{{roleName}}"
      tags: always
      loop_control:
        loop_var: "roleName"
      loop:
        - docker

- name: Media Center setup
  hosts: mediacenter
  gather_facts: no
  tasks:
    - name: Include role
      include_role:
        name: "{{roleName}}"
        apply:
          tags: "{{roleName}}"
      tags: always
      loop_control:
        loop_var: "roleName"
      loop:
        - mediacenter
