---
cloud_provider: ovh
cloud_region: eu-west-rbx
cloud_zone: eu-west-rbx-a
k8s_master_host: k8s-master.fabinfra.net
k8s_node_labels: kubernetes-host= {{cloud_provider}}-host= domain-crespel-me=true domain-jediholo-net=true server-role-ftp=true server-role-infra=true server-role-jka=true server-role-vpn=true server-role-web=true topology.kubernetes.io/region={{cloud_region}} topology.kubernetes.io/zone={{cloud_zone}}
k8s_node_role: controlplane
openvpn_server_enabled: true
