---
# Tasks for Debian

- name: Install keys
  apt_key:
    url: "{{item}}"
  loop:
    - https://pkgs.k8s.io/core:/stable:/v{{k8s_version_minor}}/deb/Release.key
    - https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{k8s_version_minor}}/deb/Release.key

- name: Install Kubernetes repository
  apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v{{k8s_version_minor}}/deb/ /
    filename: kubernetes

- name: Install CRI-O repository
  apt_repository:
    repo: deb https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{k8s_version_minor}}/deb/ /
    filename: cri-o

- name: Install WireGuard kernel module
  apt:
    name: wireguard-dkms
    state: present
  when: ansible_distribution_major_version == '11'

- name: Install packages
  apt:
    name:
      - cri-o
      - cri-tools
      - kubeadm={{k8s_version}}-*
      - kubectl={{k8s_version}}-*
      - kubelet={{k8s_version}}-*
      - wireguard
      - wireguard-tools

- name: Configure kubelet
  lineinfile:
    path: /etc/default/kubelet
    regexp: "^KUBELET_EXTRA_ARGS="
    line: "KUBELET_EXTRA_ARGS=\"--runtime-request-timeout=15m --cgroup-driver=systemd -v=2 --hostname-override={{k8s_node_name}}\""
    create: true
