---
# Tasks for Debian

- name: Install Kubernetes repository
  ansible.builtin.deb822_repository:
    name: kubernetes
    uris: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_minor }}/deb/
    suites: /
    signed_by: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_minor }}/deb/Release.key
  register: k8s_repo_result

- name: Install CRI-O repository
  ansible.builtin.deb822_repository:
    name: cri-o
    uris: https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v{{ k8s_version_minor }}/deb/
    suites: /
    signed_by: https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v{{ k8s_version_minor }}/deb/Release.key
  register: crio_repo_result

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: "k8s_repo_result.changed or crio_repo_result.changed"

- name: Install packages
  ansible.builtin.apt:
    name:
      - cri-o
      - cri-tools
      - kubeadm={{ k8s_version }}-*
      - kubectl={{ k8s_version }}-*
      - kubelet={{ k8s_version }}-*
      - wireguard
      - wireguard-tools

- name: Configure kubelet
  ansible.builtin.lineinfile:
    path: /etc/default/kubelet
    regexp: "^KUBELET_EXTRA_ARGS="
    line: "KUBELET_EXTRA_ARGS=\"--runtime-request-timeout=15m --cgroup-driver=systemd -v=2 --hostname-override={{ k8s_node_name }}\""
    create: true
    owner: root
    group: root
    mode: "0644"
