---
# Tasks for Debian

- name: Install Kubernetes repository key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_minor }}/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes.asc
    owner: root
    group: root
    mode: "0644"

- name: Install Kubernetes repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_minor }}/deb/ /
    filename: kubernetes

- name: Install CRI-O repository key
  ansible.builtin.get_url:
    url: https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v{{ k8s_version_minor }}/deb/Release.key
    dest: /etc/apt/keyrings/cri-o.asc
    owner: root
    group: root
    mode: "0644"

- name: Install CRI-O repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/cri-o.asc] https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v{{ k8s_version_minor }}/deb/ /
    filename: cri-o

- name: Install packages
  ansible.builtin.apt:
    name:
      - cri-o
      - cri-tools
      - kubeadm={{ k8s_version }}-*
      - kubectl={{ k8s_version }}-*
      - kubelet={{ k8s_version }}-*
      - wireguard
      - wireguard-tools

- name: Configure kubelet
  ansible.builtin.lineinfile:
    path: /etc/default/kubelet
    regexp: "^KUBELET_EXTRA_ARGS="
    line: "KUBELET_EXTRA_ARGS=\"--runtime-request-timeout=15m --cgroup-driver=systemd -v=2 --hostname-override={{ k8s_node_name }}\""
    create: true
    owner: root
    group: root
    mode: "0644"
