---
# Tasks for Debian 11

- name: Install keys
  apt_key:
    url: "{{item}}"
  with_items:
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_11/Release.key
    - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{k8s_version_minor}}/Debian_11/Release.key

- name: Install Libcontainers repository
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_11/ /
    filename: devel:kubic:libcontainers:stable

- name: Install Libcontainers CRI-O repository
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{k8s_version_minor}}/Debian_11/ /
    filename: devel:kubic:libcontainers:stable:cri-o:{{k8s_version_minor}}

- name: Install Kubernetes repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes

- name: Install packages
  apt:
    name:
      - cri-o
      - cri-tools
      - kubeadm={{k8s_version}}-00
      - kubectl={{k8s_version}}-00
      - kubelet={{k8s_version}}-00
      - wireguard
      - wireguard-dkms
      - wireguard-tools

- name: Configure kubelet
  lineinfile:
    path: /etc/default/kubelet
    regexp: "^KUBELET_EXTRA_ARGS="
    line: "KUBELET_EXTRA_ARGS=\"--runtime-request-timeout=15m --cgroup-driver=systemd -v=2 --cni-bin-dir=/opt/cni/bin,/usr/libexec/cni,/usr/lib/cni --hostname-override={{k8s_node_name}}\""
    create: true
