---
# Main tasks

- name: CentOS 7 setup
  include_tasks: centos7.yml
  when: ansible_distribution|lower == 'centos' and ansible_distribution_major_version == '7'

- name: Check Helm version
  shell: helm version --template {% raw %}{{.Version}}{% endraw %}
  register: helm_version_check
  ignore_errors: true
  changed_when: false

- name: Install Helm
  unarchive:
    remote_src: true
    src: https://get.helm.sh/helm-v{{helm_version}}-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts: ["--strip-components=1", "linux-amd64/helm"]
    creates: /usr/local/bin/helm
  when: helm_version_check.rc != 0 or helm_version_check.stdout != ("v" + helm_version)

- name: Check Calico CLI version
  shell: calicoctl version | grep 'Client Version:' | egrep -o 'v[0-9.]+'
  register: calico_version_check
  ignore_errors: true
  changed_when: false

- name: Install Calico CLI
  get_url:
    url: https://github.com/projectcalico/calicoctl/releases/download/v{{calico_version}}/calicoctl
    dest: /usr/local/bin/calicoctl
    mode: 0755
  when: calico_version_check.rc != 0 or calico_version_check.stdout != ("v" + calico_version)
