---
# Tasks for RedHat

- name: Install Kubernetes repository
  yum_repository:
    name: kubernetes
    description: kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v{{k8s_version_minor}}/rpm/
    gpgkey: https://pkgs.k8s.io/core:/stable:/v{{k8s_version_minor}}/rpm/repodata/repomd.xml.key
    exclude:
      - cri-tools
      - kubeadm
      - kubectl
      - kubelet
      - kubernetes-cni

- name: Install CRI-O repository
  yum_repository:
    name: cri-o
    description: CRI-O
    baseurl: https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{k8s_version_minor}}/rpm/
    gpgkey: https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{k8s_version_minor}}/rpm/repodata/repomd.xml.key

- name: Install packages
  yum:
    name:
      - cri-o
      - cri-tools
      - kubeadm-{{k8s_version}}
      - kubectl-{{k8s_version}}
      - kubelet-{{k8s_version}}
      - wireguard-tools
    disable_excludes: kubernetes
    state: present

- name: Configure kubelet
  lineinfile:
    path: /etc/sysconfig/kubelet
    regexp: "^KUBELET_EXTRA_ARGS="
    line: "KUBELET_EXTRA_ARGS=\"--runtime-request-timeout=15m --cgroup-driver=systemd -v=2 --hostname-override={{k8s_node_name}}\""
    create: true
