---
# Tasks for RedHat 7

- name: Install Libcontainers repository
  yum_repository:
    name: devel_kubic_libcontainers_stable
    description: devel_kubic_libcontainers_stable
    baseurl: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/
    gpgkey: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/repodata/repomd.xml.key

- name: Install Libcontainers CRI-O repository
  yum_repository:
    name: devel_kubic_libcontainers_stable_cri-o_{{k8s_version_minor}}
    description: devel_kubic_libcontainers_stable_cri-o_{{k8s_version_minor}}
    baseurl: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{k8s_version_minor}}/CentOS_7/
    gpgkey: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{k8s_version_minor}}/CentOS_7/repodata/repomd.xml.key

- name: Install Kubernetes repository
  yum_repository:
    name: kubernetes
    description: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude:
      - kubeadm
      - kubectl
      - kubelet

- name: Install packages
  yum:
    name:
      - cri-o
      - cri-tools
      - kmod-wireguard
      - kubeadm-{{k8s_version}}-0
      - kubectl-{{k8s_version}}-0
      - kubelet-{{k8s_version}}-0
      - wireguard-tools
    disable_excludes: kubernetes
    state: present

- name: Configure kubelet
  lineinfile:
    path: /etc/sysconfig/kubelet
    regexp: "^KUBELET_EXTRA_ARGS="
    line: "KUBELET_EXTRA_ARGS=\"--runtime-request-timeout=15m --cgroup-driver=systemd -v=2 --cni-bin-dir=/opt/cni/bin,/usr/libexec/cni,/usr/lib/cni --hostname-override={{k8s_node_name}}\""
    create: true
