---
# Tasks for Debian

- name: Install Grafana repository key
  apt_key:
    url: https://apt.grafana.com/gpg.key

- name: Install Grafana repository
  apt_repository:
    repo: deb https://apt.grafana.com stable main
    filename: grafana

- name: Install Grafana Agent
  apt:
    name: grafana-agent={{grafana_agent_version}}-1
    state: present

- name: Configure Grafana Agent service
  lineinfile:
    path: /etc/default/grafana-agent
    regexp: "^CUSTOM_ARGS="
    line: "CUSTOM_ARGS=\"-server.http.address=127.0.0.1:19090 -server.grpc.address=127.0.0.1:19091\""
