---
# Main tasks

- name: Setup RedHat
  include_tasks: redhat.yml
  when: "grafana_agent_enabled == true and ansible_os_family|lower == 'redhat'"

- name: Setup Debian
  include_tasks: debian.yml
  when: "grafana_agent_enabled == true and ansible_os_family|lower == 'debian'"

- name: Configure Grafana Agent
  template:
    src: grafana-agent.yaml.j2
    dest: /etc/grafana-agent.yaml
    mode: 0640
    owner: grafana-agent
    group: grafana-agent
  register: grafana_agent_config
  when: "grafana_agent_enabled == true and grafana_cloud_api_key|length > 0"

- name: Stop Grafana Agent service
  service:
    name: grafana-agent
    enabled: false
    state: stopped
  when: "grafana_agent_enabled == false and skip_services == false"
  ignore_errors: true

- name: Start Grafana Agent service
  service:
    name: grafana-agent
    enabled: true
    state: restarted
  when: "grafana_agent_enabled == true and grafana_agent_config.changed and skip_services == false"
