---
# Main tasks

- name: Setup RedHat
  include_tasks: redhat.yml
  when: ansible_os_family|lower == 'redhat'

- name: Setup Debian
  include_tasks: debian.yml
  when: ansible_os_family|lower == 'debian'

- name: Configure Grafana Agent
  template:
    src: grafana-agent.yaml.j2
    dest: /etc/grafana-agent.yaml
  register: grafana_agent_config
  when: grafana_cloud_api_key|length > 0

- name: Stop Grafana Agent service
  service:
    name: grafana-agent
    enabled: false
    state: stopped
  when: "grafana_agent_enabled == false and (ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest)"

- name: Start Grafana Agent service
  service:
    name: grafana-agent
    enabled: true
    state: restarted
  when: "grafana_agent_enabled == true and grafana_agent_config.changed and (ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest)"
