---
# Tasks for RedHat

- name: Install Grafana repository
  yum_repository:
    name: grafana
    description: grafana
    baseurl: https://rpm.grafana.com
    gpgkey: https://rpm.grafana.com/gpg.key
    exclude: grafana-agent

- name: Install Grafana Agent
  yum:
    name: grafana-agent-{{grafana_agent_version}}-1
    disable_excludes: grafana
    state: present

- name: Configure Grafana Agent service
  lineinfile:
    path: /etc/sysconfig/grafana-agent
    regexp: "^CUSTOM_ARGS="
    line: "CUSTOM_ARGS=\"-server.http.address=127.0.0.1:19090 -server.grpc.address=127.0.0.1:19091\""
