---
auto_update_enabled: true
autofs_enabled: false
autofs_smb_enabled: false
autofs_smb_credentials: "{{ vault_autofs_smb_credentials | default({}) }}"
dns_search: srv.fabinfra.net fabinfra.net
extra_groups: []
extra_users: []
extra_keys: []
extra_repos: []
extra_packages: []
extra_services: []
flatpaks: []
gai_prefer_ipv4: true
mounts: []
skip_services: false
skip_sysctl: false
snaps: []
sysctl_fs_inotify_max_user_instances: "8192"
sysctl_vm_max_map_count: "1048576"
sysctl_vm_swappiness: "10"
templates_enabled: true
root_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIrVE54qOR6SoNlDRrDwo2KBntH93+eedQzqmOJptUQn fabien@fab-precision3580.home.crespel.me
