---
cloud_provider: ovh
cloud_region: GRA
cloud_zone: GRA1
k8s_master_host: k8s-master.fabinfra.net
k8s_node_labels: kubernetes-host= {{cloud_provider}}-host= topology.kubernetes.io/region={{cloud_region}} topology.kubernetes.io/zone={{cloud_zone}}
k8s_node_role: worker
k8s_node_taints: dedicated-server=:NoSchedule
openvpn_server_enabled: true
