---
fail2ban_enabled: true
firewall_enabled: true
firewall_individual_calls: false
firewall_interfaces:
  - zone: vpn
    interface: tun0
firewall_ports: []
firewall_services:
  - zone: public
    service: ssh
  - zone: vpn
    service: ssh
firewall_sources: []
firewall_zones:
  - vpn
skip_services: false
