---
# Tasks for Debian

- name: Install packages
  ansible.builtin.apt:
    name:
      - kodi
      - kodi-game-libretro
      - kodi-peripheral-joystick
      - kodi-pvr-tvheadend-hts
    state: present
