---
# Main tasks

- name: Setup Debian
  ansible.builtin.include_tasks: debian.yml
  when: "kodi_enabled and ansible_facts['os_family'] | lower == 'debian'"

- name: Configure service
  ansible.builtin.template:
    src: kodi.service.j2
    dest: /etc/systemd/system/kodi.service
    owner: root
    group: root
    mode: "0644"
  when: "kodi_enabled"
  register: kodi_service

- name: Stop Kodi service
  ansible.builtin.service:
    name: kodi
    enabled: false
    state: stopped
  when: "not kodi_enabled and not skip_services"
  ignore_errors: true

- name: Start Kodi service
  ansible.builtin.service:
    name: kodi
    enabled: true
    state: restarted
  when: "kodi_enabled and kodi_service.changed and not skip_services"
