---
# Main tasks

- name: Setup Debian
  include_tasks: debian.yml
  when: "kodi_enabled == true and ansible_os_family|lower == 'debian'"

- name: Configure service
  template:
    src: kodi.service.j2
    dest: /etc/systemd/system/kodi.service
  when: "kodi_enabled == true"
  register: kodi_service

- name: Stop Kodi service
  service:
    name: kodi
    enabled: false
    state: stopped
  when: "kodi_enabled == false and skip_services == false"
  ignore_errors: true

- name: Start Kodi service
  service:
    name: kodi
    enabled: true
    state: restarted
  when: "kodi_enabled == true and kodi_service.changed and skip_services == false"
