---
# Tasks for Debian

- name: Install OpenTelemetry Collector (x86_64)
  apt:
    deb: "{{otelcol_url}}/v{{otelcol_version}}/otelcol-contrib_{{otelcol_version}}_linux_amd64.deb"
    state: present
  when: "ansible_architecture == 'x86_64'"

- name: Install OpenTelemetry Collector (aarch64)
  apt:
    deb: "{{otelcol_url}}/v{{otelcol_version}}/otelcol-contrib_{{otelcol_version}}_linux_arm64.deb"
    state: present
  when: "ansible_architecture == 'aarch64'"

- name: Install OpenTelemetry Collector (armv7l)
  apt:
    deb: "{{otelcol_url}}/v{{otelcol_version}}/otelcol-contrib_{{otelcol_version}}_linux_armv7.deb"
    state: present
  when: "ansible_architecture == 'armv7l'"
