---
# Main tasks

- name: Setup RedHat
  include_tasks: redhat.yml
  when: "otelcol_enabled == true and ansible_os_family|lower == 'redhat'"

- name: Setup Debian
  include_tasks: debian.yml
  when: "otelcol_enabled == true and ansible_os_family|lower == 'debian'"

- name: Add OpenTelemetry Collector user to systemd-journal group
  user:
    name: otelcol-contrib
    groups: [systemd-journal]
  when: "otelcol_enabled == true"

- name: Configure OpenTelemetry Collector
  template:
    src: config.yaml.j2
    dest: /etc/otelcol-contrib/config.yaml
    mode: 0640
    owner: otelcol-contrib
    group: otelcol-contrib
  register: otelcol_config
  when: "otelcol_enabled == true"

- name: Stop OpenTelemetry Collector service
  service:
    name: otelcol-contrib
    enabled: false
    state: stopped
  when: "otelcol_enabled == false and skip_services == false"
  ignore_errors: true

- name: Start OpenTelemetry Collector service
  service:
    name: otelcol-contrib
    enabled: true
    state: restarted
  when: "otelcol_enabled == true and otelcol_config.changed and skip_services == false"
