---
# Main tasks

- name: Setup RedHat
  ansible.builtin.include_tasks: redhat.yml
  when: "otelcol_enabled and ansible_os_family|lower == 'redhat'"

- name: Setup Debian
  ansible.builtin.include_tasks: debian.yml
  when: "otelcol_enabled and ansible_os_family|lower == 'debian'"

- name: Setup SUSE
  ansible.builtin.include_tasks: suse.yml
  when: "otelcol_enabled and ansible_os_family|lower == 'suse'"

- name: Create otelcol service override directory
  ansible.builtin.file:
    path: /etc/systemd/system/otelcol-contrib.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: "otelcol_enabled"

- name: Configure otelcol service
  ansible.builtin.copy:
    dest: /etc/systemd/system/otelcol-contrib.service.d/override.conf
    content: |
      [Service]
      User={{ otelcol_user }}
      Group={{ otelcol_group }}
    owner: root
    group: root
    mode: "0644"
  register: otelcol_service
  when: "otelcol_enabled"

- name: Add otelcol user to systemd-journal group
  ansible.builtin.user:
    name: "{{ otelcol_user }}"
    groups: [systemd-journal]
  when: "otelcol_enabled"

- name: Create otelcol storage directory
  ansible.builtin.file:
    path: "{{ otelcol_storage_path }}"
    owner: "{{ otelcol_user }}"
    group: "{{ otelcol_group }}"
    mode: "0755"
    state: directory
  when: "otelcol_enabled"

- name: Configure otelcol
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/otelcol-contrib/config.yaml
    owner: "{{ otelcol_user }}"
    group: "{{ otelcol_group }}"
    mode: "0640"
  register: otelcol_config
  when: "otelcol_enabled"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: "otelcol_enabled and otelcol_service.changed and not skip_services"

- name: Stop otelcol service
  ansible.builtin.service:
    name: otelcol-contrib
    enabled: false
    state: stopped
  when: "not otelcol_enabled and not skip_services"
  ignore_errors: true

- name: Start otelcol service
  ansible.builtin.service:
    name: otelcol-contrib
    enabled: true
    state: restarted
  when: "otelcol_enabled and otelcol_config.changed and not skip_services"
