---
# Tasks for SUSE

- name: Install OpenTelemetry Collector (x86_64)
  community.general.zypper:
    name: "{{otelcol_url}}/v{{otelcol_version}}/otelcol-contrib_{{otelcol_version}}_linux_amd64.rpm"
    disable_gpg_check: true
    state: present
  when: "ansible_architecture == 'x86_64'"
  ignore_errors: "{{skip_services == true}}"

- name: Install OpenTelemetry Collector (aarch64)
  community.general.zypper:
    name: "{{otelcol_url}}/v{{otelcol_version}}/otelcol-contrib_{{otelcol_version}}_linux_arm64.rpm"
    disable_gpg_check: true
    state: present
  when: "ansible_architecture == 'aarch64'"
  ignore_errors: "{{skip_services == true}}"

- name: Install OpenTelemetry Collector (armv7l)
  community.general.zypper:
    name: "{{otelcol_url}}/v{{otelcol_version}}/otelcol-contrib_{{otelcol_version}}_linux_armv7.rpm"
    disable_gpg_check: true
    state: present
  when: "ansible_architecture == 'armv7l'"
  ignore_errors: "{{skip_services == true}}"
