---
# Tasks for Debian

- name: Install Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    uris: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg
  register: docker_repo_result

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: "docker_repo_result.changed"

- name: Install packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - containerd.io
    state: present
