---
# Tasks for Debian

- name: Set repository distribution (Debian)
  set_fact:
    docker_repo_distribution: "{{ansible_distribution_release}}"
  when: ansible_distribution|lower == 'debian'

- name: Set repository distribution (Ubuntu 18-19)
  set_fact:
    docker_repo_distribution: "buster"
  when: ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version in ['18', '19']

- name: Set repository distribution (Ubuntu 20-21)
  set_fact:
    docker_repo_distribution: "bullseye"
  when: ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version in ['20', '21']

- name: Install Docker repository key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: Install Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian {{docker_repo_distribution}} stable
    filename: docker

- name: Install packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
