---
# Tasks for Debian

- name: Install Docker repository key
  apt_key:
    url: https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg

- name: Install Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    filename: docker

- name: Install packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
