---
# Main tasks

- name: Setup RedHat
  ansible.builtin.include_tasks: redhat.yml
  when: "docker_daemon_enabled and ansible_facts['os_family'] | lower == 'redhat'"

- name: Setup Debian
  ansible.builtin.include_tasks: debian.yml
  when: "docker_daemon_enabled and ansible_facts['os_family'] | lower == 'debian'"

- name: Setup SUSE
  ansible.builtin.include_tasks: suse.yml
  when: "docker_daemon_enabled and ansible_facts['os_family'] | lower == 'suse'"

- name: Create Docker storage directory
  ansible.builtin.file:
    path: "{{ docker_storage_dir }}"
    owner: root
    group: root
    mode: "0700"
    state: directory
  when: "docker_daemon_enabled"

- name: Create Docker config directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: "docker_daemon_enabled"

- name: Configure Docker daemon
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  register: docker_daemon_config
  when: "docker_daemon_enabled"

- name: Stop Docker daemon
  ansible.builtin.service:
    name: docker
    enabled: false
    state: stopped
  when: "not docker_daemon_enabled and not skip_services"
  ignore_errors: true

- name: Start Docker daemon
  ansible.builtin.service:
    name: docker
    enabled: true
    state: restarted
  when: "docker_daemon_enabled and docker_daemon_config.changed and not skip_services"

- name: Login to Docker registries
  ansible.builtin.command:
    cmd: "docker login --username {{ item.username }} --password-stdin {{ item.registry }}"
    stdin: "{{ item.password }}"
  no_log: true
  loop: "{{ docker_credentials }}"
  when: "docker_daemon_enabled and docker_credentials | length > 0"

- name: Install ctop (x86_64)
  ansible.builtin.get_url:
    url: https://github.com/bcicen/ctop/releases/download/v{{ ctop_version }}/ctop-{{ ctop_version }}-linux-amd64
    dest: /usr/local/bin/ctop
    checksum: "{{ ctop_checksum_x86_64 }}"
    owner: root
    group: root
    mode: "0755"
  when: "docker_daemon_enabled and ansible_facts['architecture'] == 'x86_64'"

- name: Install ctop (aarch64)
  ansible.builtin.get_url:
    url: https://github.com/bcicen/ctop/releases/download/v{{ ctop_version }}/ctop-{{ ctop_version }}-linux-arm64
    dest: /usr/local/bin/ctop
    checksum: "{{ ctop_checksum_aarch64 }}"
    owner: root
    group: root
    mode: "0755"
  when: "docker_daemon_enabled and ansible_facts['architecture'] == 'aarch64'"

- name: Install ctop (armv7l)
  ansible.builtin.get_url:
    url: https://github.com/bcicen/ctop/releases/download/v{{ ctop_version }}/ctop-{{ ctop_version }}-linux-arm
    dest: /usr/local/bin/ctop
    checksum: "{{ ctop_checksum_armv7l }}"
    owner: root
    group: root
    mode: "0755"
  when: "docker_daemon_enabled and ansible_facts['architecture'] == 'armv7l'"
