---
# Main tasks

- name: Setup RedHat
  include_tasks: redhat.yml
  when: "docker_daemon_enabled == true and ansible_os_family|lower == 'redhat'"

- name: Setup Debian
  include_tasks: debian.yml
  when: "docker_daemon_enabled == true and ansible_os_family|lower == 'debian'"

- name: Setup SUSE
  include_tasks: suse.yml
  when: "docker_daemon_enabled == true and ansible_os_family|lower == 'suse'"

- name: Create Docker storage directory
  file:
    path: "{{docker_storage_dir}}"
    mode: 0700
    state: directory
  when: "docker_daemon_enabled == true"

- name: Create Docker config directory
  file:
    path: /etc/docker
    state: directory
  when: "docker_daemon_enabled == true"

- name: Configure Docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  register: docker_daemon_config
  when: "docker_daemon_enabled == true"

- name: Stop Docker daemon
  service:
    name: docker
    enabled: false
    state: stopped
  when: "docker_daemon_enabled == false and skip_services == false"
  ignore_errors: true

- name: Start Docker daemon
  service:
    name: docker
    enabled: true
    state: restarted
  when: "docker_daemon_enabled == true and docker_daemon_config.changed and skip_services == false"

- name: Install ctop (x86_64)
  get_url:
    url: https://github.com/bcicen/ctop/releases/download/v{{ctop_version}}/ctop-{{ctop_version}}-linux-amd64
    dest: /usr/local/bin/ctop
    mode: 0755
  when: "docker_daemon_enabled == true and ansible_architecture == 'x86_64'"

- name: Install ctop (aarch64)
  get_url:
    url: https://github.com/bcicen/ctop/releases/download/v{{ctop_version}}/ctop-{{ctop_version}}-linux-arm64
    dest: /usr/local/bin/ctop
    mode: 0755
  when: "docker_daemon_enabled == true and ansible_architecture == 'aarch64'"

- name: Install ctop (armv7l)
  get_url:
    url: https://github.com/bcicen/ctop/releases/download/v{{ctop_version}}/ctop-{{ctop_version}}-linux-arm
    dest: /usr/local/bin/ctop
    mode: 0755
  when: "docker_daemon_enabled == true and ansible_architecture == 'armv7l'"
