---
# Tasks for RedHat

- name: Install Docker repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install packages
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
