---
# Tasks for Debian

- name: Install extra keys
  apt_key:
    url: "{{item}}"
  loop: "{{extra_keys}}"
  when: "extra_keys | length > 0"

- name: Install extra repositories
  apt_repository: "{{item}}"
  loop: "{{extra_repos}}"
  when: "extra_repos | length > 0"

- name: Install base packages
  apt:
    name:
      - autofs
      - bash-completion
      - curl
      - git
      - htop
      - iftop
      - iotop
      - jq
      - lsof
      - netcat-openbsd
      - ntp
      - openssh-server
      - postfix
      - psmisc
      - python3-pip
      - rclone
      - rsync
      - sudo
      - tmux
      - unattended-upgrades
      - unzip
      - vim
      - wget
      - zip
    state: present

- name: Install extra packages
  apt:
    name: "{{extra_packages}}"
    state: present
  when: "extra_packages | length > 0"

- name: Disable unattended-upgrades
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    src: /usr/share/unattended-upgrades/20auto-upgrades-disabled
    remote_src: true
  when: "auto_update_enabled == false"

- name: Enable unattended-upgrades
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    src: /usr/share/unattended-upgrades/20auto-upgrades
    remote_src: true
  when: "auto_update_enabled == true"
