---
# Tasks for Debian

- name: Install backports repository
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    filename: backports
  when: ansible_distribution_major_version == '10'

- name: Install packages
  apt:
    name:
      - bash-completion
      - fail2ban
      - firewalld
      - git
      - htop
      - iftop
      - iotop
      - jq
      - lsof
      - netcat
      - nscd
      - ntp
      - openssh-server
      - postfix
      - psmisc
      - python3-pip
      - rclone
      - rsync
      - sudo
      - tmux
      - unattended-upgrades
      - unzip
      - vim
      - wget
      - zip
    state: present
