---
# Main tasks

- name: Setup RedHat 7
  include_tasks: redhat7.yml
  when: ansible_os_family|lower == 'redhat' and ansible_distribution_major_version == '7'

- name: Setup Debian 10
  include_tasks: debian10.yml
  when: ansible_os_family|lower == 'debian' and ansible_distribution_major_version == '10'

- name: Setup Debian 11
  include_tasks: debian11.yml
  when: ansible_os_family|lower == 'debian' and ansible_distribution_major_version == '11'

- name: Setup SUSE 15
  include_tasks: suse15.yml
  when: ansible_os_family|lower == 'suse' and ansible_distribution_major_version == '15'

- name: Create sysadmin group
  group:
    name: sysadmin

- name: Create admin user
  user:
    name: admin
    group: users
    groups: [sysadmin]
    home: /home/users/admin
    comment: "System Admin"

- name: Configure SSH server (Banner)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Banner\\s"
    line: "Banner /etc/ssh/banner.txt"

- name: Configure SSH server (PermitRootLogin)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin\\s"
    line: "PermitRootLogin without-password"

- name: Configure SSH authorized keys
  authorized_key:
    key: "{{item}}"
    user: root
  loop: "{{root_authorized_keys}}"

- name: Configure sysctl (max_map_count)
  sysctl:
    name: vm.max_map_count
    value: "{{sysctl_vm_max_map_count}}"
  when: "ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest"

- name: Configure sysctl (swappiness)
  sysctl:
    name: vm.swappiness
    value: "{{sysctl_vm_swappiness}}"
  when: "ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest"

- name: Process template directories
  ansible.builtin.file:
    path: /{{item.path}}
    state: directory
  with_filetree: ../templates
  when: item.state == 'directory'

- name: Process template files
  template:
    src: "{{item.src}}"
    dest: "/{{item.path | splitext | first}}"
  with_filetree: ../templates
  when: item.state == 'file'
