---
# Main tasks

- name: Setup RedHat
  ansible.builtin.include_tasks: redhat.yml
  when: "ansible_os_family|lower == 'redhat'"

- name: Setup Debian
  ansible.builtin.include_tasks: debian.yml
  when: "ansible_os_family|lower == 'debian'"

- name: Setup SUSE
  ansible.builtin.include_tasks: suse.yml
  when: "ansible_os_family|lower == 'suse'"

- name: Install Flatpaks
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ flatpaks }}"
  when: "flatpaks | length > 0"

- name: Configure mount points
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts | default(omit) }}"
    state: mounted
  loop: "{{ mounts }}"

- name: Create sysadmin group
  ansible.builtin.group:
    name: sysadmin

- name: Create admin user
  ansible.builtin.user:
    name: admin
    group: users
    groups: [sysadmin]
    home: /home/admin
    comment: "System Admin"

- name: Create extra groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
  loop: "{{ extra_groups }}"

- name: Create extra users
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    home: "{{ item.home }}"
  loop: "{{ extra_users }}"

- name: Check if NetworkManager config directory exists
  ansible.builtin.stat:
    path: /etc/NetworkManager/conf.d
  register: nm_config_dir

- name: Configure NetworkManager DNS resolver
  ansible.builtin.copy:
    dest: /etc/NetworkManager/conf.d/dns.conf
    content: |
      [main]
      dns=default
    owner: root
    group: root
    mode: "0644"
  register: nm_dns_config
  when: "nm_config_dir.stat.exists"

- name: Configure resolv.conf (search)
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: "^search"
    line: "search {{ dns_search }}"
  when: "dns_search | length > 0"

- name: Configure SSH server
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/00-custom.conf
    content: |
      Banner /etc/ssh/banner.txt
      PermitRootLogin without-password
    owner: root
    group: root
    mode: "0644"

- name: Configure SSH authorized keys
  ansible.posix.authorized_key:
    key: "{{ item }}"
    user: root
  loop: "{{ root_authorized_keys }}"

- name: Configure sysctl (fs.inotify.max_user_instances)
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: "{{ sysctl_fs_inotify_max_user_instances }}"
  when: "not skip_sysctl"

- name: Configure sysctl (vm.max_map_count)
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "{{ sysctl_vm_max_map_count }}"
  when: "not skip_sysctl"

- name: Configure sysctl (vm.swappiness)
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ sysctl_vm_swappiness }}"
  when: "not skip_sysctl"

- name: Configure autofs master
  ansible.builtin.lineinfile:
    path: /etc/auto.master
    regexp: "^#\\+dir:/etc/auto\\.master\\.d"
    line: "+dir:/etc/auto.master.d"
  register: autofs_config
  when: "autofs_enabled"

- name: Enable autofs smb
  ansible.builtin.copy:
    dest: /etc/auto.master.d/smb.autofs
    content: /mnt/smb /etc/auto.smb --timeout=900
    owner: root
    group: root
    mode: "0644"
  when: "autofs_smb_enabled"

- name: Disable autofs smb
  ansible.builtin.file:
    path: /etc/auto.master.d/smb.autofs
    state: absent
  when: "not autofs_smb_enabled"

- name: Configure autofs smb credentials
  ansible.builtin.copy:
    dest: /etc/creds/{{ item.key }}
    content: |
      username={{ item.value.username }}
      password={{ item.value.password }}
      domain={{ item.value.domain | default('') }}
    owner: root
    group: root
    mode: "0640"
  no_log: true
  loop: "{{ autofs_smb_credentials | dict2items }}"
  when: "autofs_smb_enabled"

- name: Start autofs service
  ansible.builtin.service:
    name: autofs
    enabled: true
    state: restarted
  when: "autofs_enabled and autofs_config.changed and not skip_services"

- name: Stop autofs service
  ansible.builtin.service:
    name: autofs
    enabled: false
    state: stopped
  when: "not autofs_enabled and not skip_services"

- name: Process template directories
  ansible.builtin.file:
    path: /{{ item.path }}
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_community.general.filetree: ../templates
  when: "item.state == 'directory'"

- name: Process template files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/{{ item.path | splitext | first }}"
    owner: root
    group: root
    mode: "0644"
  with_community.general.filetree: ../templates
  when: "item.state == 'file'"

- name: Enable extra services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ extra_services }}"
  when: "extra_services | length > 0 and not skip_services"
