---
# Main tasks

- name: Setup RedHat
  include_tasks: redhat.yml
  when: ansible_os_family|lower == 'redhat'

- name: Setup Debian
  include_tasks: debian.yml
  when: ansible_os_family|lower == 'debian'

- name: Setup SUSE
  include_tasks: suse.yml
  when: ansible_os_family|lower == 'suse'

- name: Create sysadmin group
  group:
    name: sysadmin

- name: Create admin user
  user:
    name: admin
    group: users
    groups: [sysadmin]
    home: /home/users/admin
    comment: "System Admin"

- name: Configure resolv.conf (search)
  lineinfile:
    path: /etc/resolv.conf
    regexp: "^search"
    line: "search {{dns_search}}"
  when: "ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest"

- name: Configure SSH server (Banner)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Banner\\s"
    line: "Banner /etc/ssh/banner.txt"

- name: Configure SSH server (PermitRootLogin)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin\\s"
    line: "PermitRootLogin without-password"

- name: Configure SSH authorized keys
  authorized_key:
    key: "{{item}}"
    user: root
  loop: "{{root_authorized_keys}}"

- name: Configure sysctl (max_map_count)
  sysctl:
    name: vm.max_map_count
    value: "{{sysctl_vm_max_map_count}}"
  when: "ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest"

- name: Configure sysctl (swappiness)
  sysctl:
    name: vm.swappiness
    value: "{{sysctl_vm_swappiness}}"
  when: "ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest"

- name: Process template directories
  file:
    path: /{{item.path}}
    state: directory
  with_filetree: ../templates
  when: item.state == 'directory'

- name: Process template files
  template:
    src: "{{item.src}}"
    dest: "/{{item.path | splitext | first}}"
  with_filetree: ../templates
  when: item.state == 'file'
