---
# Tasks for RedHat

- name: Install EPEL and ELRepo repositories
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm
      - https://www.elrepo.org/elrepo-release-{{ansible_distribution_major_version}}.el{{ansible_distribution_major_version}}.elrepo.noarch.rpm
    state: present

- name: Install packages
  yum:
    name:
      - bash-completion
      - git
      - htop
      - iftop
      - iotop
      - jq
      - lsof
      - netcat
      - nscd
      - ntp
      - openssh-server
      - postfix
      - psmisc
      - python3-pip
      - rclone
      - rsync
      - sudo
      - tmux
      - unzip
      - vim-enhanced
      - wget
      - yum-cron
      - yum-plugin-elrepo
      - yum-utils
      - zip
    state: present

- name: Configure yum-cron (update_cmd)
  lineinfile:
    path: /etc/yum/yum-cron.conf
    regexp: "^update_cmd ="
    line: "update_cmd = security"

- name: Configure yum-cron (apply_updates)
  lineinfile:
    path: /etc/yum/yum-cron.conf
    regexp: "^apply_updates ="
    line: "apply_updates = yes"

- name: Disable yum-cron service
  service:
    name: yum-cron
    enabled: false
    state: stopped
  when: "auto_update_enabled == false and (ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest)"

- name: Enable yum-cron service
  service:
    name: yum-cron
    enabled: true
    state: started
  when: "auto_update_enabled == true and (ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest)"
