name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [debian12, opensuse156, opensuse160, opensusetw, rocky9, ubuntu2204]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo ${{ secrets.vault_password }} > vault.password
          ./test.sh ${{ matrix.os }}
