---
# Main tasks

- name: Setup RedHat
  include_tasks: redhat.yml
  when: ansible_os_family|lower == 'redhat'

- name: Setup Debian
  include_tasks: debian.yml
  when: ansible_os_family|lower == 'debian'

- name: Setup SUSE
  include_tasks: suse.yml
  when: ansible_os_family|lower == 'suse'

- name: Configure OpenVPN (client.conf)
  template:
    src: client.conf.j2
    dest: /etc/openvpn/client.conf
    mode: 0600
  register: openvpn_client_config
  when: openvpn_client_enabled

- name: Configure OpenVPN (server.conf)
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
    mode: 0600
  register: openvpn_server_config
  when: openvpn_server_enabled

- name: Configure OpenVPN (ipp.txt)
  template:
    src: ipp.txt.j2
    dest: /etc/openvpn/ipp.txt
  register: openvpn_ipp_config
  when: openvpn_server_enabled

- name: Stop OpenVPN client service
  service:
    name: openvpn@client
    enabled: false
    state: stopped
  when: "openvpn_client_enabled == false and (ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest)"
  ignore_errors: true

- name: Start OpenVPN client service
  service:
    name: openvpn@client
    enabled: true
    state: restarted
  when: "openvpn_client_enabled == true and openvpn_client_config.changed and (ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest)"

- name: Stop OpenVPN server service
  service:
    name: openvpn@server
    enabled: false
    state: stopped
  when: "openvpn_server_enabled == false and (ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest)"
  ignore_errors: true

- name: Start OpenVPN server service
  service:
    name: openvpn@server
    enabled: true
    state: restarted
  when: "openvpn_server_enabled == true and (openvpn_server_config.changed or openvpn_ipp_config.changed) and (ansible_virtualization_tech_guest is not defined or 'container' not in ansible_virtualization_tech_guest)"
