---
# Tasks for RedHat

- name: Install packages
  ansible.builtin.dnf:
    name:
      - openvpn
    state: present

- name: Set facts
  ansible.builtin.set_fact:
    openvpn_client_dir: /etc/openvpn/client
    openvpn_client_service: openvpn-client
    openvpn_server_dir: /etc/openvpn/server
    openvpn_server_service: openvpn-server
