---
# Tasks for SUSE

- name: Install packages
  community.general.zypper:
    name:
      - openvpn
    state: present

- name: Set facts
  ansible.builtin.set_fact:
    openvpn_client_dir: /etc/openvpn
    openvpn_client_service: openvpn
    openvpn_server_dir: /etc/openvpn
    openvpn_server_service: openvpn
